

services:
  db:
    image: postgres:16.1
    container_name: db-library
    volumes:
      - volume-library:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: georffrey
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432

volumes:
  volume-library:
    external: false
